### ISSUE TITLE
TypeError: unhashable type: 'FunctionDict'

### ISSUE THREAD

**Issue by artosa** [Skyscanner/cfripper#120]
Hi, we are trialing cfripper as part of our ci pipeline, and it feels awesome, but I have encountered a few places where it seems cfmodel fails to understand the structures, causing cfripper to fail with an exception. Most recent one, a real blocker for us, is issue with s3 bucket + policy, when policy contains s3:ListBucket.

Here's a minimal example that fails:

```
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "my-test-bucket"
  TestBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref "TestBucket"
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": ["s3:ListBucket"],
              "Effect": "Allow",
              "Resource": !GetAtt TestBucket.Arn,
              "Principal": {
                  "AWS": "aws:arn:aws:iam::00000000:user/Dave"
              }
            }
          ]
        }
```

When running with cfripper 0.18.1, we get:

> cfripper cfripper_test.yaml
Analysing cfripper_test.yaml...
Condition=None Statement=[Statement(Condition=None, Sid=None, Effect='Allow', Principal={'AWS': 'aws:arn:aws:iam::00000000:user/Dave'}, NotPrincipal=None, Action=['s3:ListBucket'], NotAction=None, Resource=FunctionDict(Fn::GetAtt=['TestBucket', 'Arn']), NotResource=None)] Version=datetime.date(2012, 10, 17)
S3BucketPublicReadAclAndListStatementRule crashed with TypeError for project - None, service - None, stack - None
Traceback (most recent call last):
  File "/home/arto/.local/lib/python3.8/site-packages/cfripper/rule_processor.py", line 22, in process_cf_template
    result += rule.invoke(cfmodel, extras)
  File "/home/arto/.local/lib/python3.8/site-packages/cfripper/rules/s3_public_access.py", line 40, in invoke
    bucket = cfmodel.Resources.get(bucket_name)
TypeError: unhashable type: 'FunctionDict'

If I replace in Bucket Policy the bucket Ref by hardcoded bucket name, like this, then it works:

```
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "my-test-bucket"
  TestBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "my-test-bucket"
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": ["s3:ListBucket"],
              "Effect": "Allow",
              "Resource": !GetAtt TestBucket.Arn,
              "Principal": {
                  "AWS": "aws:arn:aws:iam::00000000:user/Dave"
              }
            }
          ]
        }
```

I've seen at least one similar thing in the past, with cfmodel, but there was a workaround for it then, that made sense.

You can simplify this farther, but I think that bucket ref should be valid in Cloudformation, but it's not accepted by cfmodel, when using s3:ListBucket policy. Oddly enough, when we use s3:GetObject or other object level policies, they work without exception. 

Any ideas on what this might be? Right now our workaround would be to hardcode the bucket name, instead of using a ref, but it's slightly silly workaround.

**Comment by oscarbc96** [comment]
Hi @artosa!
Thanks for reporting the issue!
CFRipper has two execution modes:
- Using resolver: `cfripper --resolve test.yml`
- Standard: `cfripper test.yml`
If the `--resolve` flag is passed, then it tries to resolve all intrinsic functions inside the file.

That means that our CFRipper rules have to support both cases (but you find one that it doesn't🙄). 
So the best solution is to add a check for the raw intrinsic function inside the rule, meanwhile, the workaround would be using the resolver flag.
```
cfripper --resolve test.yml 
Analysing test.yml...
Using `UNDEFINED_PARAM_TestBucket` for TestBucket. Original value wasn't available.
`Fn::GetAtt` resolver not implemented, returning `GETATT`
Condition=None Statement=[Statement(Condition=None, Sid=None, Effect='Allow', Principal={'AWS': 'aws:arn:aws:iam::00000000:user/Dave'}, NotPrincipal=None, Action=['s3:ListBucket'], NotAction=None, Resource='GETATT', NotResource=None)] Version=datetime.date(2012, 10, 17)
Not adding S3CrossAccountTrustRule failure in TestBucketPolicy because no AWS Account ID was found in the config.
Valid: True
```
In this output 🔝, we can see `UNDEFINED_PARAM_TestBucket` because we don't have the capability  (yet) to resolve references inside the same CF. AWS when deploys a CF knows which is going to be the final ARN/Name, as we don't, we have to pass it from outside. However, CFRipper is going to use a default if we don't pass it. In this case the default is `UNDEFINED_PARAM_TestBucket`.  The following example ⬇️ uses an external file to simulate this external parameters.

```
$ cat params.json
{
  "TestBucket": "TestBucketName"
}

$ cfripper --resolve test.yml --resolve-parameters params.json                                                                                                                  Analysing test.yml...
`Fn::GetAtt` resolver not implemented, returning `GETATT`
Condition=None Statement=[Statement(Condition=None, Sid=None, Effect='Allow', Principal={'AWS': 'aws:arn:aws:iam::00000000:user/Dave'}, NotPrincipal=None, Action=['s3:ListBucket'], NotAction=None, Resource='GETATT', NotResource=None)] Version=datetime.date(2012, 10, 17)
Not adding S3CrossAccountTrustRule failure in TestBucketPolicy because no AWS Account ID was found in the config.
Valid: True
```

Hope this is helpful!

**Comment by crystoll** [comment]
Ah, yes, it was very helpful. That was excellent explanation of the mechanisms.

 Unfortunately I tried to run with --resolve flag but then there's another issue of unexpected exception elsewhere that works fine without it :) Perhaps I should do another issue on that one. It happens when resolve flag is on, using CommaDelimitedList as type, and not assigning parameter values for it with the file (AttributeError: 'NoneType' object has no attribute 'split')

But perhaps using parameter values file and --resolve flag would work for us in both cases. 

Thank you for this!

**Comment by jsoucheiron** [comment]
We can track this in the other issue. I'm closing this one
