### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by curtis-turner** [Skyscanner/cfripper#30]
Hey, I was wondering if you might be able to provide clearer instructions on how to deploy this to AWS Lambda as that is not clearly covered in your readme. Unless I am missing something really obvious. #

**Comment by vlttnv** [comment]
Hi @curtis-turner.
CFripper deploys as any other lambda function, there is nothing special about it. That's why we haven't included any instructions.
You can deploy it as a regular python package as show in the [AWS docs.](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html)

**Comment by curtis-turner** [comment]
Hey @vlttnv thanks for the response. I have deployed it as shown in the AWS Docs but I am getting a syntax error coming from s3_adapter.py line 59. Any ideas what might be causing that? Any help would be greatly appreciated.
<img width="676" alt="lambda_error_github" src="https://user-images.githubusercontent.com/25060448/54234858-3d5cff00-44cd-11e9-9381-7702d74dad53.png">

**Comment by vlttnv** [comment]
Hmm, which python version is the lambda running? It must be 3.X rather than 2.7.

**Comment by curtis-turner** [comment]
Hey @vlttnv, thanks for your help I managed to get it working after your comment about using 3.x.
